-- AUTO-GENERATED by migration/etl/schema-gen.mjs on 2026-06-16T10:29:00.630Z
-- Complete MySQL 8 schema for the MadeNKorea migration. Safe to re-run.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `wishlist_items`;
DROP TABLE IF EXISTS `whatsapp_templates`;
DROP TABLE IF EXISTS `whatsapp_contacts`;
DROP TABLE IF EXISTS `whatsapp_campaigns`;
DROP TABLE IF EXISTS `whatsapp_campaign_messages`;
DROP TABLE IF EXISTS `vendors`;
DROP TABLE IF EXISTS `vendor_members`;
DROP TABLE IF EXISTS `user_memberships`;
DROP TABLE IF EXISTS `store_settings`;
DROP TABLE IF EXISTS `store_credits`;
DROP TABLE IF EXISTS `social_schedules`;
DROP TABLE IF EXISTS `social_scheduled_posts`;
DROP TABLE IF EXISTS `shipping_zones`;
DROP TABLE IF EXISTS `role_grants`;
DROP TABLE IF EXISTS `review_votes`;
DROP TABLE IF EXISTS `referral_links`;
DROP TABLE IF EXISTS `referral_clicks`;
DROP TABLE IF EXISTS `promo_codes`;
DROP TABLE IF EXISTS `profiles`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `product_videos`;
DROP TABLE IF EXISTS `product_translations`;
DROP TABLE IF EXISTS `product_story_blocks`;
DROP TABLE IF EXISTS `product_reviews`;
DROP TABLE IF EXISTS `product_images`;
DROP TABLE IF EXISTS `product_country_prices`;
DROP TABLE IF EXISTS `pincodes`;
DROP TABLE IF EXISTS `pincode_serviceability_cache`;
DROP TABLE IF EXISTS `payments`;
DROP TABLE IF EXISTS `payment_orders`;
DROP TABLE IF EXISTS `password_reset_tokens`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `order_items`;
DROP TABLE IF EXISTS `order_attributions`;
DROP TABLE IF EXISTS `order_attribution_items`;
DROP TABLE IF EXISTS `notification_recipients`;
DROP TABLE IF EXISTS `membership_plans`;
DROP TABLE IF EXISTS `k_partnership_videos`;
DROP TABLE IF EXISTS `invoices`;
DROP TABLE IF EXISTS `invoice_units`;
DROP TABLE IF EXISTS `invoice_payments`;
DROP TABLE IF EXISTS `invoice_items`;
DROP TABLE IF EXISTS `invoice_counters`;
DROP TABLE IF EXISTS `invoice_companies`;
DROP TABLE IF EXISTS `invoice_batch_items`;
DROP TABLE IF EXISTS `invoice_addresses`;
DROP TABLE IF EXISTS `inventory_units_bulk_delete_audit`;
DROP TABLE IF EXISTS `inventory_units`;
DROP TABLE IF EXISTS `inventory_events`;
DROP TABLE IF EXISTS `international_orders`;
DROP TABLE IF EXISTS `instagram_messages`;
DROP TABLE IF EXISTS `instagram_media_posts`;
DROP TABLE IF EXISTS `instagram_conversations`;
DROP TABLE IF EXISTS `instagram_comments`;
DROP TABLE IF EXISTS `instagram_accounts`;
DROP TABLE IF EXISTS `influencer_requests`;
DROP TABLE IF EXISTS `influencer_profiles`;
DROP TABLE IF EXISTS `influencer_payouts`;
DROP TABLE IF EXISTS `influence_caps`;
DROP TABLE IF EXISTS `home_product_videos`;
DROP TABLE IF EXISTS `home_product_video_products`;
DROP TABLE IF EXISTS `home_influencer_videos`;
DROP TABLE IF EXISTS `home_influencer_video_products`;
DROP TABLE IF EXISTS `home_banners`;
DROP TABLE IF EXISTS `facebook_page_posts`;
DROP TABLE IF EXISTS `facebook_page_comments`;
DROP TABLE IF EXISTS `facebook_insights`;
DROP TABLE IF EXISTS `facebook_campaigns`;
DROP TABLE IF EXISTS `facebook_adsets`;
DROP TABLE IF EXISTS `facebook_ads`;
DROP TABLE IF EXISTS `events`;
DROP TABLE IF EXISTS `email_verification_tokens`;
DROP TABLE IF EXISTS `email_unsubscribe`;
DROP TABLE IF EXISTS `email_contact_category`;
DROP TABLE IF EXISTS `email_contact`;
DROP TABLE IF EXISTS `email_change_requests`;
DROP TABLE IF EXISTS `email_category`;
DROP TABLE IF EXISTS `email_campaign_recipient`;
DROP TABLE IF EXISTS `email_campaign_category`;
DROP TABLE IF EXISTS `email_campaign`;
DROP TABLE IF EXISTS `dtdc_tracking_tokens`;
DROP TABLE IF EXISTS `dtdc_shipments`;
DROP TABLE IF EXISTS `dtdc_shipment_events`;
DROP TABLE IF EXISTS `dtdc_api_logs`;
DROP TABLE IF EXISTS `customers`;
DROP TABLE IF EXISTS `currency_rates`;
DROP TABLE IF EXISTS `country_shipping_rates`;
DROP TABLE IF EXISTS `country_contacts`;
DROP TABLE IF EXISTS `contact_messages`;
DROP TABLE IF EXISTS `category_translations`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `carts`;
DROP TABLE IF EXISTS `cart_items`;
DROP TABLE IF EXISTS `campaigns`;
DROP TABLE IF EXISTS `campaign_posts`;
DROP TABLE IF EXISTS `brands`;
DROP TABLE IF EXISTS `brand_translations`;
DROP TABLE IF EXISTS `batches`;
DROP TABLE IF EXISTS `banner_translations`;
DROP TABLE IF EXISTS `app_admins`;
DROP TABLE IF EXISTS `admin_notifications`;
DROP TABLE IF EXISTS `admin_notification_reads`;
DROP TABLE IF EXISTS `addresses`;
DROP TABLE IF EXISTS `_delete_debug`;

CREATE TABLE `_delete_debug` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `msg` MEDIUMTEXT NULL,
  `constr` MEDIUMTEXT NULL,
  `ts` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `addresses` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `line1` MEDIUMTEXT NOT NULL,
  `line2` MEDIUMTEXT NULL,
  `city` MEDIUMTEXT NOT NULL,
  `state` MEDIUMTEXT NOT NULL,
  `pincode` MEDIUMTEXT NOT NULL,
  `country` VARCHAR(512) NOT NULL DEFAULT 'India',
  `is_default` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` MEDIUMTEXT NULL,
  `phone` MEDIUMTEXT NULL,
  `email` MEDIUMTEXT NULL,
  `landmark` MEDIUMTEXT NULL,
  KEY `addresses_default_unique` (`user_id`),
  PRIMARY KEY (`id`),
  KEY `addresses_user_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `admin_notification_reads` (
  `notification_id` CHAR(36) NOT NULL,
  `admin_id` CHAR(36) NOT NULL,
  `read_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`notification_id`, `admin_id`),
  KEY `idx_anr_admin_id` (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `admin_notifications` (
  `id` CHAR(36) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `title` MEDIUMTEXT NOT NULL,
  `body` MEDIUMTEXT NULL,
  `link` MEDIUMTEXT NULL,
  `severity` VARCHAR(512) NOT NULL DEFAULT 'info',
  `meta` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by` CHAR(36) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_admin_notifications_created_at` (`created_at`),
  KEY `idx_admin_notifications_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `app_admins` (
  `user_id` CHAR(36) NOT NULL,
  `email` VARCHAR(255) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY `app_admins_email_key` (`email`),
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `banner_translations` (
  `id` CHAR(36) NOT NULL,
  `banner_id` CHAR(36) NOT NULL,
  `locale` VARCHAR(255) NOT NULL,
  `title` MEDIUMTEXT NULL,
  `alt` MEDIUMTEXT NULL,
  `source_hash` MEDIUMTEXT NULL,
  `source` VARCHAR(512) NOT NULL DEFAULT 'ai',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY `banner_translations_banner_id_locale_key` (`banner_id`, `locale`),
  KEY `banner_translations_lookup` (`banner_id`, `locale`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `batches` (
  `id` CHAR(36) NOT NULL,
  `batch_code` VARCHAR(255) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `quantity` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `expiry_date` DATE NOT NULL,
  `status` VARCHAR(512) NULL DEFAULT 'IN_STOCK',
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY `batches_batch_code_key` (`batch_code`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `brand_translations` (
  `id` CHAR(36) NOT NULL,
  `brand_id` CHAR(36) NOT NULL,
  `locale` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `source_hash` MEDIUMTEXT NULL,
  `source` VARCHAR(512) NOT NULL DEFAULT 'ai',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY `brand_translations_brand_id_locale_key` (`brand_id`, `locale`),
  KEY `brand_translations_lookup` (`brand_id`, `locale`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `brands` (
  `id` CHAR(36) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `thumbnail_path` MEDIUMTEXT NULL,
  `thumbnail_url` MEDIUMTEXT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `position` INT NOT NULL DEFAULT 10,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `brand_code` VARCHAR(255) NULL,
  UNIQUE KEY `brands_brand_code_idx` (`brand_code`),
  UNIQUE KEY `brands_brand_code_key` (`brand_code`),
  PRIMARY KEY (`id`),
  KEY `brands_position_idx` (`position`),
  UNIQUE KEY `brands_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `campaign_posts` (
  `id` CHAR(36) NOT NULL,
  `campaign_id` CHAR(36) NOT NULL,
  `instagram_account_id` CHAR(36) NOT NULL,
  `caption` MEDIUMTEXT NULL,
  `media_type` VARCHAR(64) NOT NULL DEFAULT 'image',
  `media_url` MEDIUMTEXT NULL,
  `thumbnail_url` MEDIUMTEXT NULL,
  `scheduled_at` DATETIME(6) NULL,
  `published_at` DATETIME(6) NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `instagram_media_id` MEDIUMTEXT NULL,
  `permalink` MEDIUMTEXT NULL,
  `error_message` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `campaigns` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `instagram_account_id` CHAR(36) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cart_items` (
  `id` CHAR(36) NOT NULL,
  `cart_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `sku` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `hero_image_path` MEDIUMTEXT NULL,
  `unit_price` DECIMAL(12,2) NOT NULL,
  `mrp` DECIMAL(12,2) NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `line_total` DECIMAL(12,2) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `cart_items_cart_idx` (`cart_id`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `cart_items_unique` (`cart_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `carts` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `shipping_fee_estimate` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discount_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `total_estimate` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `carts_user_idx` (`user_id`),
  UNIQUE KEY `carts_user_unique` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `categories` (
  `id` CHAR(36) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `parent_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `category_translations` (
  `id` CHAR(36) NOT NULL,
  `category_id` CHAR(36) NOT NULL,
  `locale` VARCHAR(255) NOT NULL,
  `name` MEDIUMTEXT NULL,
  `description` MEDIUMTEXT NULL,
  `source_hash` MEDIUMTEXT NULL,
  `source` VARCHAR(512) NOT NULL DEFAULT 'ai',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY `category_translations_category_id_locale_key` (`category_id`, `locale`),
  KEY `category_translations_lookup` (`category_id`, `locale`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `contact_messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  `email` MEDIUMTEXT NOT NULL,
  `phone` MEDIUMTEXT NULL,
  `subject` MEDIUMTEXT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `status` VARCHAR(512) NOT NULL DEFAULT 'new',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `country_contacts` (
  `country_code` VARCHAR(255) NOT NULL,
  `public_phone` MEDIUMTEXT NULL,
  `whatsapp_number` MEDIUMTEXT NULL,
  `support_email` MEDIUMTEXT NULL,
  `business_hours` MEDIUMTEXT NULL,
  `public_address` MEDIUMTEXT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by` CHAR(36) NULL,
  `contact_name` MEDIUMTEXT NULL,
  PRIMARY KEY (`country_code`),
  KEY `idx_country_contacts_active` (`country_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `country_shipping_rates` (
  `country` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `notes` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `eta_days_min` INT NULL,
  `eta_days_max` INT NULL,
  `slab_500g_inr` DECIMAL(10,2) NOT NULL,
  `slab_1kg_inr` DECIMAL(10,2) NOT NULL,
  `slab_2kg_inr` DECIMAL(10,2) NOT NULL,
  `slab_3kg_inr` DECIMAL(10,2) NOT NULL,
  `slab_5kg_inr` DECIMAL(10,2) NOT NULL,
  `slab_7kg_inr` DECIMAL(10,2) NOT NULL,
  `slab_10kg_inr` DECIMAL(10,2) NOT NULL,
  `slab_15kg_inr` DECIMAL(10,2) NOT NULL,
  `slab_20kg_inr` DECIMAL(10,2) NOT NULL,
  KEY `country_shipping_rates_active_idx` (`active`),
  PRIMARY KEY (`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `currency_rates` (
  `code` VARCHAR(255) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `symbol` MEDIUMTEXT NOT NULL,
  `decimals` INT NOT NULL DEFAULT 2,
  `rate_from_inr` DECIMAL(20,6) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `last_updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `customers` (
  `id` CHAR(36) NOT NULL,
  `vendor_id` CHAR(36) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `phone` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `address` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `customers_vendor_email_idx` (`vendor_id`, `email`),
  KEY `customers_vendor_email_unique` (`vendor_id`, `email`),
  KEY `customers_vendor_id_idx` (`vendor_id`),
  KEY `customers_vendor_phone_idx` (`vendor_id`, `phone`),
  KEY `customers_vendor_phone_unique` (`vendor_id`, `phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `dtdc_api_logs` (
  `id` CHAR(36) NOT NULL,
  `shipment_id` CHAR(36) NULL,
  `api_name` MEDIUMTEXT NOT NULL,
  `endpoint` MEDIUMTEXT NULL,
  `request` JSON NULL,
  `response` JSON NULL,
  `http_status` INT NULL,
  `success` TINYINT(1) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_dtdc_api_logs_created_at` (`created_at`),
  KEY `idx_dtdc_api_logs_shipment_id` (`shipment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `dtdc_shipment_events` (
  `id` CHAR(36) NOT NULL,
  `shipment_id` CHAR(36) NOT NULL,
  `event_at` DATETIME(6) NULL,
  `action` VARCHAR(255) NULL,
  `status_code` MEDIUMTEXT NULL,
  `origin` MEDIUMTEXT NULL,
  `destination` MEDIUMTEXT NULL,
  `remarks` MEDIUMTEXT NULL,
  `raw` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_dtdc_events_event_at` (`event_at`),
  KEY `idx_dtdc_events_shipment_id` (`shipment_id`),
  UNIQUE KEY `uniq_dtdc_events_dedup` (`shipment_id`, `event_at`, `action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `dtdc_shipments` (
  `id` CHAR(36) NOT NULL,
  `order_id` CHAR(36) NOT NULL,
  `reference_number` VARCHAR(255) NULL,
  `customer_code` MEDIUMTEXT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `service_type_id` MEDIUMTEXT NULL,
  `commodity_id` MEDIUMTEXT NULL,
  `load_type` MEDIUMTEXT NULL,
  `is_cod` TINYINT(1) NOT NULL DEFAULT 0,
  `cod_amount` DECIMAL(12,2) NULL,
  `weight_kg` DECIMAL(10,3) NULL,
  `length_cm` DECIMAL(10,2) NULL,
  `breadth_cm` DECIMAL(10,2) NULL,
  `height_cm` DECIMAL(10,2) NULL,
  `last_label_code` MEDIUMTEXT NULL,
  `last_label_format` MEDIUMTEXT NULL,
  `label_last_generated_at` DATETIME(6) NULL,
  `dtdc_request` JSON NULL,
  `dtdc_response` JSON NULL,
  `last_error` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `last_polled_at` DATETIME(6) NULL,
  `status_last_changed_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dtdc_shipments_active_poll` (`is_active`, `last_polled_at`),
  KEY `idx_dtdc_shipments_order_id` (`order_id`),
  KEY `idx_dtdc_shipments_status` (`status`),
  KEY `uniq_dtdc_shipments_active_order` (`order_id`),
  KEY `uniq_dtdc_shipments_reference_number` (`reference_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `dtdc_tracking_tokens` (
  `id` CHAR(36) NOT NULL,
  `env` VARCHAR(255) NOT NULL,
  `token` MEDIUMTEXT NOT NULL,
  `expires_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_dtdc_tracking_tokens_env` (`env`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_campaign` (
  `id` CHAR(36) NOT NULL,
  `subject` MEDIUMTEXT NOT NULL,
  `body_html` MEDIUMTEXT NOT NULL,
  `target_type` VARCHAR(64) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by` CHAR(36) NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `send_started_at` DATETIME(6) NULL,
  `send_completed_at` DATETIME(6) NULL,
  KEY `email_campaign_created_at_idx` (`created_at`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_campaign_category` (
  `campaign_id` CHAR(36) NOT NULL,
  `category_id` CHAR(36) NOT NULL,
  KEY `email_campaign_category_campaign_idx` (`campaign_id`),
  KEY `email_campaign_category_category_idx` (`category_id`),
  PRIMARY KEY (`campaign_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_campaign_recipient` (
  `id` CHAR(36) NOT NULL,
  `campaign_id` CHAR(36) NOT NULL,
  `contact_id` CHAR(36) NULL,
  `email` MEDIUMTEXT NOT NULL,
  `name` MEDIUMTEXT NULL,
  `is_registered` TINYINT(1) NOT NULL DEFAULT 0,
  `status` VARCHAR(64) NOT NULL DEFAULT 'pending',
  `error` MEDIUMTEXT NULL,
  `sent_at` DATETIME(6) NULL,
  `ses_message_id` MEDIUMTEXT NULL,
  `delivery_event` VARCHAR(64) NULL,
  `delivery_event_at` DATETIME(6) NULL,
  `delivery_event_payload` JSON NULL,
  `has_opened` TINYINT(1) NOT NULL DEFAULT 0,
  `opened_at` DATETIME(6) NULL,
  `has_clicked` TINYINT(1) NOT NULL DEFAULT 0,
  `clicked_at` DATETIME(6) NULL,
  `last_engagement_payload` JSON NULL,
  KEY `email_campaign_recipient_campaign_idx` (`campaign_id`),
  PRIMARY KEY (`id`),
  KEY `email_campaign_recipient_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_category` (
  `id` CHAR(36) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `label` MEDIUMTEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_category_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_change_requests` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `current_email` MEDIUMTEXT NOT NULL,
  `requested_email` MEDIUMTEXT NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `reason` MEDIUMTEXT NULL,
  `admin_note` MEDIUMTEXT NULL,
  `requested_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `processed_at` DATETIME(6) NULL,
  `processed_by` CHAR(36) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ecr_requested_at` (`requested_at`),
  KEY `idx_ecr_status` (`status`),
  KEY `idx_ecr_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_contact` (
  `id` CHAR(36) NOT NULL,
  `email` MEDIUMTEXT NOT NULL,
  `name` MEDIUMTEXT NULL,
  `is_registered` TINYINT(1) NOT NULL DEFAULT 0,
  `registered_user_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `source` VARCHAR(512) NULL DEFAULT 'manual',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_contact_category` (
  `contact_id` CHAR(36) NOT NULL,
  `category_id` CHAR(36) NOT NULL,
  KEY `email_contact_category_category_idx` (`category_id`),
  KEY `email_contact_category_contact_idx` (`contact_id`),
  PRIMARY KEY (`contact_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_unsubscribe` (
  `id` CHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `source` VARCHAR(512) NULL DEFAULT 'user',
  `campaign_id` CHAR(36) NULL,
  KEY `email_unsubscribe_email_idx` (`email`),
  UNIQUE KEY `email_unsubscribe_email_key` (`email`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email_verification_tokens` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `email` MEDIUMTEXT NOT NULL,
  `token_hash` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  `used_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_verification_tokens_token_hash_key` (`token_hash`),
  KEY `idx_evt_expires_at` (`expires_at`),
  KEY `idx_evt_used_at` (`used_at`),
  KEY `idx_evt_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `events` (
  `id` CHAR(36) NOT NULL,
  `occurred_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `user_id` CHAR(36) NULL,
  `anon_id` VARCHAR(255) NOT NULL,
  `session_id` VARCHAR(255) NOT NULL,
  `event_name` VARCHAR(255) NOT NULL,
  `path` MEDIUMTEXT NULL,
  `referrer` MEDIUMTEXT NULL,
  `user_agent` MEDIUMTEXT NULL,
  `ip_prefix` MEDIUMTEXT NULL,
  `utm` JSON NULL,
  `device` JSON NULL,
  `props` JSON NOT NULL DEFAULT (CAST('{}' AS JSON)),
  KEY `events_anon_time_idx` (`anon_id`, `occurred_at`),
  KEY `events_name_time_idx` (`event_name`, `occurred_at`),
  KEY `events_occurred_at_idx` (`occurred_at`),
  PRIMARY KEY (`id`),
  KEY `events_session_idx` (`session_id`),
  KEY `events_user_time_idx` (`user_id`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `facebook_ads` (
  `id` CHAR(36) NOT NULL,
  `adset_id` CHAR(36) NOT NULL,
  `fb_ad_id` VARCHAR(255) NOT NULL,
  `name` MEDIUMTEXT NULL,
  `creative_id` MEDIUMTEXT NULL,
  `status` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_fb_ads_fbid` (`fb_ad_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `facebook_adsets` (
  `id` CHAR(36) NOT NULL,
  `campaign_id` CHAR(36) NOT NULL,
  `fb_adset_id` VARCHAR(255) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `optimization_goal` MEDIUMTEXT NULL,
  `billing_event` MEDIUMTEXT NULL,
  `bid_amount` INT NULL,
  `daily_budget` INT NULL,
  `start_time` DATETIME(6) NULL,
  `end_time` DATETIME(6) NULL,
  `status` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_fb_adsets_fbid` (`fb_adset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `facebook_campaigns` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `fb_campaign_id` VARCHAR(255) NOT NULL,
  `fb_ad_account_id` MEDIUMTEXT NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `status` MEDIUMTEXT NULL,
  `objective` MEDIUMTEXT NULL,
  `daily_budget` INT NULL,
  `created_time` DATETIME(6) NULL,
  `updated_time` DATETIME(6) NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_fb_campaigns_fbid` (`fb_campaign_id`),
  KEY `idx_fb_campaigns_owner` (`owner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `facebook_insights` (
  `id` CHAR(36) NOT NULL,
  `fb_object_id` VARCHAR(255) NOT NULL,
  `object_type` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `impressions` BIGINT NULL,
  `clicks` BIGINT NULL,
  `spend` DECIMAL(20,6) NULL,
  `reach` BIGINT NULL,
  `cpm` DECIMAL(20,6) NULL,
  `cpc` DECIMAL(20,6) NULL,
  `ctr` DECIMAL(20,6) NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_fb_insights_object` (`fb_object_id`, `object_type`, `date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `facebook_page_comments` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `facebook_page_id` MEDIUMTEXT NOT NULL,
  `fb_post_id` VARCHAR(255) NOT NULL,
  `fb_comment_id` VARCHAR(255) NOT NULL,
  `parent_comment_id` MEDIUMTEXT NULL,
  `message` MEDIUMTEXT NULL,
  `from_id` MEDIUMTEXT NULL,
  `from_name` MEDIUMTEXT NULL,
  `created_time` DATETIME(6) NULL,
  `like_count` INT NULL,
  `comment_count` INT NULL,
  `is_hidden` TINYINT(1) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY `facebook_page_comments_owner_comment_unique` (`owner_id`, `fb_comment_id`),
  PRIMARY KEY (`id`),
  KEY `facebook_page_comments_post_idx` (`owner_id`, `fb_post_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `facebook_page_posts` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `facebook_page_id` VARCHAR(255) NOT NULL,
  `fb_post_id` VARCHAR(255) NOT NULL,
  `message` MEDIUMTEXT NULL,
  `permalink_url` MEDIUMTEXT NULL,
  `created_time` DATETIME(6) NULL,
  `impressions` BIGINT NULL,
  `reach` BIGINT NULL,
  `engagement` BIGINT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `attachments` JSON NULL,
  `insights` JSON NULL,
  `reactions_count` INT NULL,
  `comments_count` INT NULL,
  KEY `facebook_page_posts_owner_page_idx` (`owner_id`, `facebook_page_id`),
  UNIQUE KEY `facebook_page_posts_owner_post_unique` (`owner_id`, `fb_post_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `home_banners` (
  `id` CHAR(36) NOT NULL,
  `title` MEDIUMTEXT NULL,
  `alt` MEDIUMTEXT NOT NULL,
  `image_path` MEDIUMTEXT NULL,
  `link_url` MEDIUMTEXT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `starts_at` DATETIME(6) NULL,
  `ends_at` DATETIME(6) NULL,
  `position` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `page_scope` VARCHAR(255) NOT NULL DEFAULT 'home',
  `video_url` MEDIUMTEXT NULL,
  `country` VARCHAR(255) NOT NULL DEFAULT 'IN',
  KEY `home_banners_active_idx` (`active`, `position`),
  KEY `home_banners_active_page_idx` (`active`, `page_scope`, `position`),
  KEY `home_banners_country_scope_idx` (`country`, `page_scope`, `position`),
  UNIQUE KEY `home_banners_page_country_position_uniq` (`page_scope`, `country`, `position`),
  PRIMARY KEY (`id`),
  KEY `home_banners_time_idx` (`starts_at`, `ends_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `home_influencer_video_products` (
  `video_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `position` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY `hivp_product_idx` (`product_id`),
  PRIMARY KEY (`video_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `home_influencer_videos` (
  `id` CHAR(36) NOT NULL,
  `influencer_name` MEDIUMTEXT NOT NULL,
  `influencer_handle` MEDIUMTEXT NULL,
  `caption` MEDIUMTEXT NULL,
  `views` BIGINT NOT NULL DEFAULT 0,
  `video_url` MEDIUMTEXT NULL,
  `thumbnail_url` MEDIUMTEXT NULL,
  `instagram_link` MEDIUMTEXT NULL,
  `page_scope` VARCHAR(255) NOT NULL DEFAULT 'home',
  `position` INT NOT NULL DEFAULT 10,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `starts_at` DATETIME(6) NULL,
  `ends_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `post_url` MEDIUMTEXT NULL,
  `embed_captioned` TINYINT(1) NOT NULL DEFAULT 0,
  KEY `hiv_active_scope_idx` (`active`, `page_scope`, `position`),
  KEY `hiv_schedule_idx` (`starts_at`, `ends_at`),
  UNIQUE KEY `home_influencer_scope_position_uniq` (`page_scope`, `position`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `home_product_video_products` (
  `video_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `position` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`video_id`, `product_id`),
  KEY `hpvp_product_idx` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `home_product_videos` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NULL,
  `title` MEDIUMTEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `page_scope` VARCHAR(255) NOT NULL DEFAULT 'home',
  `position` INT NOT NULL DEFAULT 10,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `starts_at` DATETIME(6) NULL,
  `ends_at` DATETIME(6) NULL,
  `video_path` MEDIUMTEXT NULL,
  `video_url` MEDIUMTEXT NULL,
  `thumbnail_path` MEDIUMTEXT NULL,
  `thumbnail_url` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `home_product_videos_scope_position_uniq` (`page_scope`, `position`),
  KEY `hpv_active_scope_idx` (`active`, `page_scope`, `position`),
  KEY `hpv_product_idx` (`product_id`),
  KEY `hpv_schedule_idx` (`starts_at`, `ends_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `influence_caps` (
  `product_id` CHAR(36) NOT NULL,
  `cap_percent` DECIMAL(5,2) NOT NULL DEFAULT 20.00,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `influencer_payouts` (
  `id` CHAR(36) NOT NULL,
  `influencer_id` CHAR(36) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `covering_orders` JSON NOT NULL DEFAULT (CAST('[]' AS JSON)),
  `status` VARCHAR(255) NOT NULL DEFAULT 'initiated',
  `notes` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `paid_at` DATETIME(6) NULL,
  `method` VARCHAR(512) NULL DEFAULT 'manual',
  `request_note` MEDIUMTEXT NULL,
  `contact_email` MEDIUMTEXT NULL,
  `settled_reference` MEDIUMTEXT NULL,
  KEY `idx_influencer_payouts_user_status_created` (`influencer_id`, `status`, `created_at`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `influencer_profiles` (
  `user_id` CHAR(36) NOT NULL,
  `handle` VARCHAR(255) NOT NULL,
  `display_name` MEDIUMTEXT NULL,
  `avatar_url` MEDIUMTEXT NULL,
  `social` JSON NULL DEFAULT (CAST('{}' AS JSON)),
  `default_commission_percent` DECIMAL(5,2) NOT NULL DEFAULT 10.00,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `payout_meta` JSON NULL DEFAULT (CAST('{}' AS JSON)),
  `display_currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `commission_cap_pct` SMALLINT NOT NULL,
  `default_user_discount_pct` SMALLINT NOT NULL,
  `applicable_countries` JSON NOT NULL DEFAULT (CAST('[]' AS JSON)),
  UNIQUE KEY `influencer_profiles_handle_key` (`handle`),
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `influencer_requests` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `handle` MEDIUMTEXT NULL,
  `social` JSON NOT NULL DEFAULT (CAST('{}' AS JSON)),
  `note` MEDIUMTEXT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `reviewed_by` CHAR(36) NULL,
  `reviewed_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `idx_influencer_requests_status` (`status`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `influencer_requests_user_unique` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `instagram_accounts` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `ig_business_account_id` VARCHAR(255) NOT NULL,
  `username` MEDIUMTEXT NULL,
  `account_type` MEDIUMTEXT NULL,
  `profile_picture_url` MEDIUMTEXT NULL,
  `access_token` MEDIUMTEXT NULL,
  `token_expires_at` DATETIME(6) NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `facebook_page_id` MEDIUMTEXT NULL,
  `page_access_token` MEDIUMTEXT NULL,
  KEY `instagram_accounts_one_active_per_owner` (`owner_id`),
  UNIQUE KEY `instagram_accounts_owner_ig_business_unique` (`owner_id`, `ig_business_account_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `instagram_comments` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `ig_business_account_id` MEDIUMTEXT NOT NULL,
  `ig_media_id` VARCHAR(255) NOT NULL,
  `ig_comment_id` VARCHAR(255) NOT NULL,
  `from_username` MEDIUMTEXT NULL,
  `message` MEDIUMTEXT NULL,
  `is_hidden` TINYINT(1) NOT NULL DEFAULT 0,
  `like_count` INT NULL,
  `created_time` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `instagram_comments_media_idx` (`ig_media_id`),
  UNIQUE KEY `instagram_comments_owner_comment_unique` (`owner_id`, `ig_comment_id`),
  KEY `instagram_comments_owner_idx` (`owner_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `instagram_conversations` (
  `id` CHAR(36) NOT NULL,
  `instagram_account_id` CHAR(36) NOT NULL,
  `ig_conversation_id` VARCHAR(255) NOT NULL,
  `participant_ig_user_id` MEDIUMTEXT NOT NULL,
  `participant_username` MEDIUMTEXT NULL,
  `participant_profile_pic_url` MEDIUMTEXT NULL,
  `last_message` MEDIUMTEXT NULL,
  `last_message_at` DATETIME(6) NULL,
  `unread_count` INT NULL DEFAULT 0,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `platform` VARCHAR(512) NOT NULL DEFAULT 'instagram',
  UNIQUE KEY `instagram_conversations_ig_id_unique` (`ig_conversation_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `instagram_media_posts` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `ig_business_account_id` VARCHAR(255) NOT NULL,
  `ig_media_id` VARCHAR(255) NOT NULL,
  `caption` MEDIUMTEXT NULL,
  `media_type` MEDIUMTEXT NULL,
  `media_url` MEDIUMTEXT NULL,
  `thumbnail_url` MEDIUMTEXT NULL,
  `permalink` MEDIUMTEXT NULL,
  `like_count` INT NULL,
  `comments_count` INT NULL,
  `timestamp` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `instagram_media_ig_id_idx` (`ig_business_account_id`),
  KEY `instagram_media_owner_idx` (`owner_id`),
  UNIQUE KEY `instagram_media_owner_media_unique` (`owner_id`, `ig_media_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `instagram_messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conversation_id` CHAR(36) NOT NULL,
  `ig_message_id` VARCHAR(255) NOT NULL,
  `sender_type` VARCHAR(64) NOT NULL,
  `sender_ig_user_id` MEDIUMTEXT NULL,
  `sender_username` MEDIUMTEXT NULL,
  `message_type` VARCHAR(512) NOT NULL DEFAULT 'text',
  `text` MEDIUMTEXT NULL,
  `media_url` MEDIUMTEXT NULL,
  `sent_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `platform` VARCHAR(512) NOT NULL DEFAULT 'instagram',
  UNIQUE KEY `instagram_messages_ig_id_unique` (`ig_message_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `international_orders` (
  `id` CHAR(36) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'new',
  `customer_name` MEDIUMTEXT NOT NULL,
  `customer_email` MEDIUMTEXT NOT NULL,
  `customer_phone` MEDIUMTEXT NULL,
  `country` MEDIUMTEXT NOT NULL,
  `address` JSON NOT NULL,
  `cart_snapshot` JSON NOT NULL,
  `currency_code` MEDIUMTEXT NOT NULL,
  `display_total` DECIMAL(20,6) NULL,
  `inr_total` DECIMAL(20,6) NULL,
  `notes` MEDIUMTEXT NULL,
  `user_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `international_orders_status_idx` (`status`, `created_at`),
  KEY `international_orders_user_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_events` (
  `id` CHAR(36) NOT NULL,
  `unit_id` CHAR(36) NOT NULL,
  `action` MEDIUMTEXT NOT NULL,
  `from_status` VARCHAR(64) NULL,
  `to_status` VARCHAR(64) NULL,
  `note` MEDIUMTEXT NULL,
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_units` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `vendor_id` CHAR(36) NULL,
  `unit_code` VARCHAR(255) NOT NULL,
  `mfg_date` DATE NULL,
  `exp_date` DATE NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'IN_STOCK',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `price` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `manufacture_date` DATE NOT NULL,
  `expiry_date` DATE NOT NULL,
  `batch_code` MEDIUMTEXT NULL,
  `brand_id` CHAR(36) NULL,
  `sold_customer_id` CHAR(36) NULL,
  `sold_customer_name` MEDIUMTEXT NULL,
  `sold_customer_phone` MEDIUMTEXT NULL,
  `sold_customer_email` MEDIUMTEXT NULL,
  `sold_customer_address` MEDIUMTEXT NULL,
  `sold_at` DATETIME(6) NULL,
  `batch_id` CHAR(36) NULL,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `verified_at` DATETIME(6) NULL,
  `verified_by` CHAR(36) NULL,
  `demo_customer_id` CHAR(36) NULL,
  `demo_customer_name` MEDIUMTEXT NULL,
  `demo_customer_phone` MEDIUMTEXT NULL,
  `demo_at` DATETIME(6) NULL,
  `sold_invoice_id` CHAR(36) NULL,
  `scan_code` VARCHAR(255) NULL,
  `sold_order_id` CHAR(36) NULL,
  `sold_channel` MEDIUMTEXT NULL,
  KEY `idx_inventory_units_product_id` (`product_id`),
  KEY `idx_inventory_units_sold_order` (`sold_order_id`),
  KEY `idx_inventory_units_status` (`status`),
  KEY `idx_inventory_units_vendor_id` (`vendor_id`),
  KEY `inventory_units_batch_id_idx` (`batch_id`),
  KEY `inventory_units_brand_id_idx` (`brand_id`),
  PRIMARY KEY (`id`),
  KEY `inventory_units_product_scan_status_created_idx` (`product_id`, `scan_code`, `status`, `created_at`),
  UNIQUE KEY `inventory_units_unit_code_key` (`unit_code`),
  KEY `inventory_units_vendor_product_scan_code_idx` (`vendor_id`, `product_id`, `scan_code`),
  KEY `inventory_units_vendor_scan_code_idx` (`vendor_id`, `scan_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_units_bulk_delete_audit` (
  `id` CHAR(36) NOT NULL,
  `vendor_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `scope` MEDIUMTEXT NOT NULL,
  `total_units` INT NOT NULL,
  `verified_units` INT NOT NULL,
  `deleted_by_name` MEDIUMTEXT NOT NULL,
  `deleted_by_email` MEDIUMTEXT NULL,
  `deleted_by_user_id` CHAR(36) NULL,
  `is_admin_override` TINYINT(1) NOT NULL DEFAULT 0,
  `filters` JSON NULL,
  `selected_ids` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `deleted_units` INT NULL,
  `skipped_verified_units` INT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_addresses` (
  `id` CHAR(36) NOT NULL,
  `vendor_id` CHAR(36) NOT NULL,
  `label` MEDIUMTEXT NOT NULL,
  `name` MEDIUMTEXT NULL,
  `phone` MEDIUMTEXT NULL,
  `email` MEDIUMTEXT NULL,
  `gstin` MEDIUMTEXT NULL,
  `address_line1` MEDIUMTEXT NOT NULL,
  `address_line2` MEDIUMTEXT NULL,
  `city` MEDIUMTEXT NOT NULL,
  `state` MEDIUMTEXT NOT NULL,
  `pincode` MEDIUMTEXT NOT NULL,
  `country` VARCHAR(512) NOT NULL DEFAULT 'India',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `category` MEDIUMTEXT NULL,
  KEY `idx_invoice_addresses_vendor` (`vendor_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_batch_items` (
  `id` CHAR(36) NOT NULL,
  `invoice_id` CHAR(36) NOT NULL,
  `batch_id` CHAR(36) NOT NULL,
  `batch_code` VARCHAR(255) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discount_per_unit` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discount_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `line_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `invoice_batch_items_batch_code_idx` (`batch_code`),
  KEY `invoice_batch_items_batch_id_idx` (`batch_id`),
  UNIQUE KEY `invoice_batch_items_invoice_batch_unique` (`invoice_id`, `batch_id`),
  KEY `invoice_batch_items_invoice_id_idx` (`invoice_id`),
  PRIMARY KEY (`id`),
  KEY `invoice_batch_items_product_id_idx` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_companies` (
  `id` CHAR(36) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `display_name` MEDIUMTEXT NOT NULL,
  `legal_name` MEDIUMTEXT NULL,
  `address` MEDIUMTEXT NULL,
  `gst_number` MEDIUMTEXT NULL,
  `pan_number` MEDIUMTEXT NULL,
  `bank_name` MEDIUMTEXT NULL,
  `bank_branch` MEDIUMTEXT NULL,
  `account_number` MEDIUMTEXT NULL,
  `ifsc_code` MEDIUMTEXT NULL,
  `swift_code` MEDIUMTEXT NULL,
  `phone` MEDIUMTEXT NULL,
  `email` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY `invoice_companies_key_key` (`key`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_counters` (
  `company_id` CHAR(36) NOT NULL,
  `year` INT NOT NULL,
  `counter` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`company_id`, `year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_items` (
  `id` CHAR(36) NOT NULL,
  `invoice_id` CHAR(36) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `hsn_sac` MEDIUMTEXT NULL,
  `quantity` DECIMAL(12,2) NOT NULL DEFAULT 1,
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `tax_percent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `line_subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `line_tax_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `line_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `position` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `product_id` CHAR(36) NULL,
  `brand` MEDIUMTEXT NULL,
  `hsn` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_payments` (
  `id` CHAR(36) NOT NULL,
  `invoice_id` CHAR(36) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `method` MEDIUMTEXT NULL,
  `reference` MEDIUMTEXT NULL,
  `note` MEDIUMTEXT NULL,
  `paid_at` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY `idx_invoice_payments_invoice` (`invoice_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_units` (
  `id` CHAR(36) NOT NULL,
  `invoice_id` CHAR(36) NOT NULL,
  `unit_id` CHAR(36) NOT NULL,
  `unit_code` VARCHAR(255) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `scan_code` VARCHAR(255) NULL,
  KEY `invoice_units_invoice_id_idx` (`invoice_id`),
  KEY `invoice_units_invoice_scan_code_idx` (`invoice_id`, `scan_code`),
  PRIMARY KEY (`id`),
  KEY `invoice_units_product_id_idx` (`product_id`),
  UNIQUE KEY `invoice_units_unit_code_uniq` (`unit_code`),
  UNIQUE KEY `invoice_units_unit_id_uniq` (`unit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoices` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `invoice_number` VARCHAR(255) NOT NULL,
  `invoice_date` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `due_date` DATE NULL,
  `customer_name` MEDIUMTEXT NOT NULL,
  `billing_address` MEDIUMTEXT NULL,
  `phone` MEDIUMTEXT NULL,
  `email` MEDIUMTEXT NULL,
  `contact_person` MEDIUMTEXT NULL,
  `gst_number` MEDIUMTEXT NULL,
  `pan_number` MEDIUMTEXT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `tax_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `notes` MEDIUMTEXT NULL,
  `status` VARCHAR(512) NOT NULL DEFAULT 'DRAFT',
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `tax_label` MEDIUMTEXT NULL,
  `is_custom` TINYINT(1) NOT NULL DEFAULT 1,
  `bill_to_address_id` CHAR(36) NULL,
  `discount_total` DECIMAL(20,6) NULL DEFAULT 0,
  `tax_type` VARCHAR(512) NULL DEFAULT 'CGST_SGST',
  `cgst_percent` DECIMAL(20,6) NULL DEFAULT 0,
  `sgst_percent` DECIMAL(20,6) NULL DEFAULT 0,
  `igst_percent` DECIMAL(20,6) NULL DEFAULT 0,
  `cgst_amount` DECIMAL(20,6) NULL DEFAULT 0,
  `sgst_amount` DECIMAL(20,6) NULL DEFAULT 0,
  `igst_amount` DECIMAL(20,6) NULL DEFAULT 0,
  `grand_total` DECIMAL(20,6) NULL,
  `invoice_seq` BIGINT NULL,
  `amount_paid` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `payment_status` VARCHAR(512) NOT NULL DEFAULT 'UNPAID',
  `paid_at` DATETIME(6) NULL,
  `last_reminder_at` DATETIME(6) NULL,
  `deleted_at` DATETIME(6) NULL,
  `deleted_by` CHAR(36) NULL,
  `last_email_at` DATETIME(6) NULL,
  KEY `idx_invoices_deleted_at` (`deleted_at`),
  UNIQUE KEY `invoices_invoice_number_key` (`invoice_number`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `k_partnership_videos` (
  `country_code` VARCHAR(255) NOT NULL,
  `storage_path` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`country_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `membership_plans` (
  `id` CHAR(36) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `duration_days` INT NOT NULL DEFAULT 90,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY `membership_plans_code_key` (`code`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_recipients` (
  `id` CHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `label` MEDIUMTEXT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `notification_recipients_active_idx` (`active`),
  UNIQUE KEY `notification_recipients_email_unique` (`email`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_attribution_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` CHAR(36) NOT NULL,
  `influencer_id` CHAR(36) NOT NULL,
  `promo_code_id` CHAR(36) NULL,
  `product_id` CHAR(36) NOT NULL,
  `qty` INT NOT NULL,
  `unit_price` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `effective_user_discount_pct` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `effective_commission_pct` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `commission_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY `idx_oai_influencer` (`influencer_id`),
  KEY `idx_oai_order` (`order_id`),
  KEY `idx_oai_product` (`product_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_attributions` (
  `order_id` CHAR(36) NOT NULL,
  `influencer_id` CHAR(36) NOT NULL,
  `referral_id` CHAR(36) NULL,
  `promo_code_id` CHAR(36) NULL,
  `attributed_by` MEDIUMTEXT NOT NULL,
  `discount_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `commission_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `commission_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `status` VARCHAR(512) NOT NULL DEFAULT 'approved',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `user_discount_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `commission_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  KEY `idx_oa_influencer_created` (`influencer_id`, `created_at`),
  KEY `idx_order_attr_influencer` (`influencer_id`),
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_items` (
  `id` CHAR(36) NOT NULL,
  `order_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NULL,
  `sku` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `hero_image_path` MEDIUMTEXT NULL,
  `unit_price` DECIMAL(12,2) NOT NULL,
  `mrp` DECIMAL(12,2) NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `line_total` DECIMAL(12,2) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY `order_items_order_idx` (`order_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `orders` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `order_number` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending_payment',
  `currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `shipping_fee` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discount_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `shipping_address_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `address_snapshot` JSON NULL,
  `notes` MEDIUMTEXT NULL,
  `promo_code_id` CHAR(36) NULL,
  `promo_snapshot` JSON NOT NULL DEFAULT (CAST('{}' AS JSON)),
  `payment_provider` MEDIUMTEXT NULL,
  `payment_reference` MEDIUMTEXT NULL,
  `payment_meta` JSON NULL,
  `paid_at` DATETIME(6) NULL,
  `fx_rate_snapshot` DECIMAL(20,6) NULL,
  `subtotal_inr` DECIMAL(20,6) NULL,
  `shipping_fee_inr` DECIMAL(20,6) NULL,
  `discount_total_inr` DECIMAL(20,6) NULL,
  `total_inr` DECIMAL(20,6) NULL,
  `recipient_locale` MEDIUMTEXT NULL,
  KEY `idx_orders_created_status` (`created_at`, `status`),
  KEY `idx_orders_promo_code_id` (`promo_code_id`),
  KEY `orders_created_idx` (`created_at`),
  UNIQUE KEY `orders_order_number_key` (`order_number`),
  PRIMARY KEY (`id`),
  KEY `orders_user_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `password_reset_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `token_hash` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  `used_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY `idx_password_reset_tokens_email` (`email`),
  KEY `idx_password_reset_tokens_token_hash` (`token_hash`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payment_orders` (
  `id` CHAR(36) NOT NULL,
  `order_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(512) NOT NULL DEFAULT 'razorpay',
  `provider_order_id` VARCHAR(255) NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `status` VARCHAR(512) NOT NULL DEFAULT 'created',
  `receipt` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY `payment_orders_order_idx` (`order_id`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_orders_provider_order_id_key` (`provider_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payments` (
  `id` CHAR(36) NOT NULL,
  `order_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(512) NOT NULL DEFAULT 'razorpay',
  `provider_payment_id` VARCHAR(255) NULL,
  `provider_order_id` MEDIUMTEXT NULL,
  `method` MEDIUMTEXT NULL,
  `status` VARCHAR(512) NOT NULL DEFAULT 'captured',
  `amount` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(512) NOT NULL DEFAULT 'INR',
  `signature` MEDIUMTEXT NULL,
  `raw` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `captured_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY `payments_order_idx` (`order_id`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `payments_provider_payment_id_key` (`provider_payment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pincode_serviceability_cache` (
  `pincode` VARCHAR(255) NOT NULL,
  `serviceable` TINYINT(1) NOT NULL,
  `eta_days_min` INT NULL,
  `eta_days_max` INT NULL,
  `payload` JSON NULL,
  `last_checked_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `source` VARCHAR(512) NOT NULL DEFAULT 'shipsy',
  PRIMARY KEY (`pincode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pincodes` (
  `pincode` VARCHAR(255) NOT NULL,
  `place_name` MEDIUMTEXT NOT NULL,
  `district` MEDIUMTEXT NULL,
  `state` VARCHAR(255) NOT NULL,
  `zone` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`pincode`),
  KEY `pincodes_state_idx` (`state`),
  KEY `pincodes_zone_idx` (`zone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_country_prices` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `country_code` VARCHAR(255) NOT NULL,
  `offer_price` DECIMAL(12,2) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `idx_pcp_country_active` (`country_code`, `is_active`),
  KEY `idx_pcp_product` (`product_id`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `product_country_prices_product_id_country_code_key` (`product_id`, `country_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_images` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `storage_path` VARCHAR(255) NOT NULL,
  `alt` MEDIUMTEXT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `product_images_product_idx` (`product_id`),
  KEY `product_images_product_sort` (`product_id`, `sort_order`),
  KEY `product_images_sort_idx` (`sort_order`),
  UNIQUE KEY `product_images_unique_per_path` (`product_id`, `storage_path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_reviews` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NULL,
  `rating` SMALLINT NOT NULL,
  `title` MEDIUMTEXT NULL,
  `body` MEDIUMTEXT NULL,
  `photos` JSON NULL DEFAULT (CAST('[]' AS JSON)),
  `is_verified_purchase` TINYINT(1) NOT NULL DEFAULT 0,
  `status` VARCHAR(255) NOT NULL DEFAULT 'published',
  `helpful_count` INT NOT NULL DEFAULT 0,
  `reported_count` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `display_name` MEDIUMTEXT NULL,
  `avatar_url` MEDIUMTEXT NULL,
  `country` VARCHAR(255) NULL,
  KEY `idx_product_reviews_country` (`country`),
  KEY `idx_product_reviews_product_country` (`product_id`, `country`),
  KEY `idx_reviews_product_status_created` (`product_id`, `status`, `created_at`),
  KEY `idx_reviews_rating` (`rating`),
  KEY `idx_reviews_user` (`user_id`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_review_per_product` (`product_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_story_blocks` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `position` INT NOT NULL,
  `block_type` MEDIUMTEXT NOT NULL,
  `size` VARCHAR(512) NOT NULL DEFAULT '2x1',
  `mode` VARCHAR(512) NOT NULL DEFAULT 'A',
  `headline` MEDIUMTEXT NULL,
  `body` MEDIUMTEXT NULL,
  `text_position` VARCHAR(512) NULL DEFAULT 'bottom-left',
  `text_color` VARCHAR(512) NULL DEFAULT 'light',
  `split_direction` VARCHAR(512) NULL DEFAULT 'image-left',
  `image_path` MEDIUMTEXT NULL,
  `image_alt` MEDIUMTEXT NULL,
  `caption` MEDIUMTEXT NULL,
  `stats_items` JSON NULL,
  `before_image_path` MEDIUMTEXT NULL,
  `after_image_path` MEDIUMTEXT NULL,
  `comparison_caption` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `text_size` VARCHAR(512) NULL DEFAULT 'md',
  `image_focal_x` DECIMAL(20,6) NULL,
  `image_focal_y` DECIMAL(20,6) NULL,
  `text_bg` MEDIUMTEXT NULL,
  `image_fit` VARCHAR(512) NULL DEFAULT 'cover',
  `image_zoom` DECIMAL(20,6) NULL DEFAULT 1,
  `image_bg` MEDIUMTEXT NULL,
  `caption_mode` VARCHAR(512) NULL DEFAULT 'always',
  `caption_backdrop` TINYINT(1) NOT NULL DEFAULT 0,
  `text_weight` VARCHAR(512) NULL DEFAULT 'bold',
  KEY `idx_psb_product_position` (`product_id`, `position`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_translations` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `locale` VARCHAR(255) NOT NULL,
  `short_description` MEDIUMTEXT NULL,
  `description` MEDIUMTEXT NULL,
  `ingredients_md` MEDIUMTEXT NULL,
  `additional_details_md` MEDIUMTEXT NULL,
  `key_features_md` MEDIUMTEXT NULL,
  `box_contents_md` MEDIUMTEXT NULL,
  `faq` JSON NULL,
  `key_benefits` JSON NULL,
  `additional_details` JSON NULL,
  `source_hash` MEDIUMTEXT NULL,
  `source` VARCHAR(512) NOT NULL DEFAULT 'ai',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `product_translations_lookup` (`product_id`, `locale`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `product_translations_product_id_locale_key` (`product_id`, `locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_videos` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `storage_path` VARCHAR(255) NOT NULL,
  `thumbnail_path` MEDIUMTEXT NULL,
  `alt` MEDIUMTEXT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `product_videos_product_id_sort_idx` (`product_id`, `sort_order`),
  UNIQUE KEY `product_videos_storage_path_uniq` (`product_id`, `storage_path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `products` (
  `id` CHAR(36) NOT NULL,
  `sku` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `short_description` MEDIUMTEXT NULL,
  `description` MEDIUMTEXT NULL,
  `brand` MEDIUMTEXT NULL,
  `price` DECIMAL(12,2) NULL,
  `currency` VARCHAR(512) NULL DEFAULT 'INR',
  `country_of_origin` MEDIUMTEXT NULL,
  `volume_ml` DECIMAL(10,2) NULL,
  `net_weight_g` DECIMAL(10,2) NULL,
  `attributes` JSON NOT NULL DEFAULT (CAST('{}' AS JSON)),
  `category_id` CHAR(36) NOT NULL,
  `hero_image_path` MEDIUMTEXT NULL,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `brand_id` CHAR(36) NULL,
  `compare_at_price` DECIMAL(12,2) NULL,
  `sale_price` DECIMAL(12,2) NULL,
  `sale_starts_at` DATETIME(6) NULL,
  `sale_ends_at` DATETIME(6) NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_trending` TINYINT(1) NOT NULL DEFAULT 0,
  `featured_rank` INT NULL,
  `new_until` DATETIME(6) NULL,
  `meta_title` MEDIUMTEXT NULL,
  `meta_description` MEDIUMTEXT NULL,
  `og_image_path` MEDIUMTEXT NULL,
  `views_count` BIGINT NOT NULL DEFAULT 0,
  `purchases_count` BIGINT NOT NULL DEFAULT 0,
  `last_viewed_at` DATETIME(6) NULL,
  `last_purchased_at` DATETIME(6) NULL,
  `deleted_at` DATETIME(6) NULL,
  `vendor_id` CHAR(36) NULL,
  `track_inventory` TINYINT(1) NOT NULL DEFAULT 1,
  `stock_qty` INT NOT NULL DEFAULT 0,
  `ingredients_md` MEDIUMTEXT NULL,
  `additional_details_md` MEDIUMTEXT NULL,
  `key_features_md` MEDIUMTEXT NULL,
  `faq` JSON NOT NULL DEFAULT (CAST('[]' AS JSON)),
  `key_benefits` JSON NOT NULL DEFAULT (CAST('[]' AS JSON)),
  `additional_details` JSON NOT NULL DEFAULT (CAST('{}' AS JSON)),
  `made_in_korea` TINYINT(1) NOT NULL DEFAULT 0,
  `is_vegetarian` TINYINT(1) NOT NULL DEFAULT 0,
  `cruelty_free` TINYINT(1) NOT NULL DEFAULT 0,
  `toxin_free` TINYINT(1) NOT NULL DEFAULT 0,
  `paraben_free` TINYINT(1) NOT NULL DEFAULT 0,
  `video_path` MEDIUMTEXT NULL,
  `promo_exempt` TINYINT(1) NOT NULL DEFAULT 0,
  `expiry_date` DATE NULL,
  `product_code` VARCHAR(255) NULL,
  `brand_code` MEDIUMTEXT NULL,
  `hsn` MEDIUMTEXT NULL,
  `box_contents_md` MEDIUMTEXT NULL,
  `is_bundle` TINYINT(1) NOT NULL DEFAULT 0,
  `gross_weight_g` DECIMAL(8,2) NULL,
  `inventory_product_id` CHAR(36) NULL,
  `purchase_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  KEY `idx_products_inventory_product` (`inventory_product_id`),
  KEY `idx_products_vendor_expiry_date` (`vendor_id`, `expiry_date`),
  KEY `products_brand_id_idx` (`brand_id`),
  KEY `products_category_idx` (`category_id`),
  KEY `products_featured_idx` (`featured_rank`),
  KEY `products_is_bundle_idx` (`is_bundle`),
  KEY `products_new_until_idx` (`new_until`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `products_product_code_idx` (`product_code`),
  UNIQUE KEY `products_product_code_key` (`product_code`),
  KEY `products_pub_created_idx` (`is_published`, `created_at`),
  UNIQUE KEY `products_sku_key` (`sku`),
  UNIQUE KEY `products_slug_key` (`slug`),
  KEY `products_trending_idx` (`is_trending`),
  KEY `products_vendor_idx` (`vendor_id`),
  FULLTEXT KEY `products_ft` (`name`, `short_description`, `description`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `profiles` (
  `id` CHAR(36) NOT NULL,
  `full_name` MEDIUMTEXT NULL,
  `avatar_url` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `phone` MEDIUMTEXT NULL,
  `default_address_id` CHAR(36) NULL,
  `role` VARCHAR(512) NOT NULL DEFAULT 'customer',
  `tracking_consent` TINYINT(1) NOT NULL DEFAULT 1,
  `preferred_locale` VARCHAR(255) NULL,
  `preferred_country` MEDIUMTEXT NULL,
  `email_verified_at` DATETIME(6) NULL,
  `email_verification_grace_starts_at` DATETIME(6) NULL,
  `email_verification_deadline_override` DATETIME(6) NULL,
  KEY `idx_profiles_email_verified_at` (`email_verified_at`),
  PRIMARY KEY (`id`),
  KEY `profiles_preferred_locale_idx` (`preferred_locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `promo_codes` (
  `id` CHAR(36) NOT NULL,
  `influencer_id` CHAR(36) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `product_id` CHAR(36) NULL,
  `discount_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `commission_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `cap_percent` DECIMAL(5,2) NOT NULL,
  `starts_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `expires_at` DATETIME(6) NULL,
  `max_uses` INT NULL,
  `uses` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `scope` VARCHAR(512) NOT NULL DEFAULT 'global',
  KEY `idx_promo_codes_code` (`code`),
  UNIQUE KEY `promo_codes_code_key` (`code`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `referral_clicks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `referral_id` CHAR(36) NOT NULL,
  `clicked_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `viewer_user_id` CHAR(36) NULL,
  `session_id` CHAR(36) NULL,
  `user_agent` MEDIUMTEXT NULL,
  `ip_hash` MEDIUMTEXT NULL,
  `meta` JSON NULL DEFAULT (CAST('{}' AS JSON)),
  KEY `idx_referral_clicks_clicked_at` (`clicked_at`),
  KEY `idx_referral_clicks_ref` (`referral_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `referral_links` (
  `id` CHAR(36) NOT NULL,
  `influencer_id` CHAR(36) NOT NULL,
  `link_type` VARCHAR(512) NOT NULL DEFAULT 'product',
  `product_id` CHAR(36) NULL,
  `code` VARCHAR(255) NOT NULL,
  `discount_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `commission_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `cap_percent` DECIMAL(5,2) NOT NULL,
  `expires_at` DATETIME(6) NULL,
  `max_uses` INT NULL,
  `uses` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY `referral_links_code_key` (`code`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `review_votes` (
  `review_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `is_helpful` TINYINT(1) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`review_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role_grants` (
  `user_id` CHAR(36) NOT NULL,
  `role` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `shipping_zones` (
  `zone` VARCHAR(255) NOT NULL,
  `label` MEDIUMTEXT NOT NULL,
  `eta_days_min` INT NOT NULL,
  `eta_days_max` INT NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by` CHAR(36) NULL,
  PRIMARY KEY (`zone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `social_scheduled_posts` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `platform` MEDIUMTEXT NOT NULL,
  `message` MEDIUMTEXT NULL,
  `media_url` MEDIUMTEXT NULL,
  `media_type` MEDIUMTEXT NULL,
  `scheduled_at` DATETIME(6) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `last_error` MEDIUMTEXT NULL,
  `posted_at` DATETIME(6) NULL,
  `fb_post_id` MEDIUMTEXT NULL,
  `ig_media_id` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `channel` MEDIUMTEXT NULL,
  `payload` JSON NOT NULL DEFAULT (CAST('{}' AS JSON)),
  `error_message` MEDIUMTEXT NULL,
  KEY `social_scheduled_posts_pending_idx` (`status`, `scheduled_at`),
  PRIMARY KEY (`id`),
  KEY `social_scheduled_posts_status_scheduled_idx` (`status`, `scheduled_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `social_schedules` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `platform` MEDIUMTEXT NOT NULL,
  `message` MEDIUMTEXT NULL,
  `media_url` MEDIUMTEXT NULL,
  `media_type` MEDIUMTEXT NULL,
  `scheduled_at` DATETIME(6) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `last_error` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `idx_social_schedules_owner` (`owner_id`),
  KEY `idx_social_schedules_status_time` (`status`, `scheduled_at`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `store_credits` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `balance` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(512) NULL DEFAULT 'INR',
  `expires_at` DATETIME(6) NULL,
  `status` VARCHAR(512) NULL DEFAULT 'active',
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY `store_credits_code_key` (`code`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `store_settings` (
  `id` SMALLINT NOT NULL DEFAULT 1,
  `delivery_threshold` INT NOT NULL DEFAULT 2000,
  `default_shipping_fee` INT NOT NULL DEFAULT 149,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by` CHAR(36) NULL,
  `legal_entity_name` MEDIUMTEXT NULL,
  `registered_address` MEDIUMTEXT NULL,
  `public_phone` MEDIUMTEXT NULL,
  `support_email` MEDIUMTEXT NULL,
  `business_hours` MEDIUMTEXT NULL,
  `grievance_officer_name` MEDIUMTEXT NULL,
  `grievance_officer_designation` MEDIUMTEXT NULL,
  `grievance_officer_email` MEDIUMTEXT NULL,
  `gstin` MEDIUMTEXT NULL,
  `cdsco_registration` MEDIUMTEXT NULL,
  `jurisdiction_city` MEDIUMTEXT NULL,
  `marketplace_disclosure_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `home_video_limit` INT NOT NULL DEFAULT 16,
  `commission_auto_approve_days` INT NOT NULL DEFAULT 0,
  `intl_packaging_tare_pct` SMALLINT NOT NULL DEFAULT 15,
  `intl_buffer_pct` SMALLINT NOT NULL DEFAULT 20,
  `intl_max_shipping_weight_kg` SMALLINT NOT NULL DEFAULT 20,
  `k_partnership_default_country` MEDIUMTEXT NULL,
  `brand_legal_entity_name` MEDIUMTEXT NULL,
  `brand_registered_address` MEDIUMTEXT NULL,
  `brand_country_code` MEDIUMTEXT NULL,
  `partner_role_label` VARCHAR(512) NOT NULL DEFAULT 'Authorized Importer & Distribution Partner',
  `email_verification_grace_days` INT NOT NULL DEFAULT 7,
  `email_verification_lockout_days` INT NOT NULL DEFAULT 30,
  `cookie_consent_delay_seconds` INT NOT NULL DEFAULT 7,
  `cookie_consent_scroll_threshold` INT NOT NULL DEFAULT 1,
  `brand_email` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_memberships` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `plan_code` VARCHAR(512) NOT NULL DEFAULT 'k_plus',
  `plan_name` VARCHAR(512) NOT NULL DEFAULT 'K-Plus',
  `amount` DECIMAL(10,2) NOT NULL DEFAULT 199,
  `duration_days` INT NOT NULL DEFAULT 90,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `starts_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `ends_at` DATETIME(6) NOT NULL,
  `payment_id` MEDIUMTEXT NULL,
  `order_id` MEDIUMTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `user_memberships_user_status_idx` (`user_id`, `status`, `ends_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vendor_members` (
  `vendor_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `role` VARCHAR(512) NOT NULL DEFAULT 'owner',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`vendor_id`, `user_id`),
  KEY `vendor_members_user_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vendors` (
  `id` CHAR(36) NOT NULL,
  `owner_profile_id` CHAR(36) NOT NULL,
  `display_name` MEDIUMTEXT NOT NULL,
  `legal_name` MEDIUMTEXT NULL,
  `slug` VARCHAR(255) NULL,
  `email` MEDIUMTEXT NULL,
  `phone` MEDIUMTEXT NULL,
  `gstin` MEDIUMTEXT NULL,
  `website` MEDIUMTEXT NULL,
  `address_json` JSON NULL,
  `status` VARCHAR(512) NOT NULL DEFAULT 'pending',
  `rejected_reason` MEDIUMTEXT NULL,
  `approved_by` CHAR(36) NULL,
  `approved_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `commission_rate` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `expiry_alert_days` INT NOT NULL DEFAULT 180,
  KEY `vendors_owner_idx` (`owner_profile_id`),
  PRIMARY KEY (`id`),
  UNIQUE KEY `vendors_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `whatsapp_campaign_messages` (
  `id` CHAR(36) NOT NULL,
  `campaign_id` CHAR(36) NOT NULL,
  `contact_id` CHAR(36) NOT NULL,
  `to_phone` MEDIUMTEXT NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'queued',
  `provider_message_id` MEDIUMTEXT NULL,
  `error_message` MEDIUMTEXT NULL,
  `sent_at` DATETIME(6) NULL,
  `delivered_at` DATETIME(6) NULL,
  `read_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY `whatsapp_campaign_messages_campaign_id_idx` (`campaign_id`),
  PRIMARY KEY (`id`),
  KEY `whatsapp_campaign_messages_status_idx` (`status`),
  UNIQUE KEY `whatsapp_campaign_messages_unique_contact` (`campaign_id`, `contact_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `whatsapp_campaigns` (
  `id` CHAR(36) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `template_id` CHAR(36) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `filter_tags` JSON NULL,
  `target_segment_description` MEDIUMTEXT NULL,
  `total_target_count` INT NULL,
  `scheduled_at` DATETIME(6) NULL,
  `started_at` DATETIME(6) NULL,
  `completed_at` DATETIME(6) NULL,
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `audience_mode` MEDIUMTEXT NULL,
  `sending_mode` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  KEY `whatsapp_campaigns_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `whatsapp_contacts` (
  `id` CHAR(36) NOT NULL,
  `full_name` MEDIUMTEXT NULL,
  `phone_e164` VARCHAR(255) NOT NULL,
  `country_code` MEDIUMTEXT NULL,
  `tags` JSON NULL DEFAULT (CAST('[]' AS JSON)),
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY `whatsapp_contacts_phone_unique` (`phone_e164`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `whatsapp_templates` (
  `id` CHAR(36) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `provider_template_name` MEDIUMTEXT NOT NULL,
  `category` MEDIUMTEXT NOT NULL,
  `language_code` VARCHAR(512) NOT NULL DEFAULT 'en',
  `header` MEDIUMTEXT NULL,
  `body` MEDIUMTEXT NULL,
  `body_preview` MEDIUMTEXT NULL,
  `example_variables` JSON NULL DEFAULT (CAST('[]' AS JSON)),
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wishlist_items` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `note` MEDIUMTEXT NULL,
  `priority` INT NOT NULL DEFAULT 3,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `wishlist_product_idx` (`product_id`),
  KEY `wishlist_user_idx` (`user_id`),
  UNIQUE KEY `wishlist_user_product_uniq` (`user_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `instagram_accounts` ADD CONSTRAINT `instagram_accounts_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `profiles` ADD CONSTRAINT `profiles_default_address_fkey` FOREIGN KEY (`default_address_id`) REFERENCES `addresses` (`id`) ON DELETE SET NULL;
ALTER TABLE `referral_links` ADD CONSTRAINT `referral_links_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL;
ALTER TABLE `influence_caps` ADD CONSTRAINT `influence_caps_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `categories` ADD CONSTRAINT `categories_parent_id_fkey` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL;
ALTER TABLE `campaigns` ADD CONSTRAINT `campaigns_instagram_account_id_fkey` FOREIGN KEY (`instagram_account_id`) REFERENCES `instagram_accounts` (`id`) ON DELETE CASCADE;
ALTER TABLE `campaigns` ADD CONSTRAINT `campaigns_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `addresses` ADD CONSTRAINT `addresses_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `campaign_posts` ADD CONSTRAINT `campaign_posts_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `campaign_posts` ADD CONSTRAINT `campaign_posts_instagram_account_id_fkey` FOREIGN KEY (`instagram_account_id`) REFERENCES `instagram_accounts` (`id`) ON DELETE CASCADE;
ALTER TABLE `order_items` ADD CONSTRAINT `order_items_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE;
ALTER TABLE `order_items` ADD CONSTRAINT `order_items_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL;
ALTER TABLE `product_images` ADD CONSTRAINT `product_images_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `vendors` ADD CONSTRAINT `vendors_approved_by_fkey` FOREIGN KEY (`approved_by`) REFERENCES `profiles` (`id`) ON DELETE NO ACTION;
ALTER TABLE `vendors` ADD CONSTRAINT `vendors_owner_profile_id_fkey` FOREIGN KEY (`owner_profile_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `vendor_members` ADD CONSTRAINT `vendor_members_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `vendor_members` ADD CONSTRAINT `vendor_members_vendor_id_fkey` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE CASCADE;
ALTER TABLE `instagram_conversations` ADD CONSTRAINT `instagram_conversations_instagram_account_id_fkey` FOREIGN KEY (`instagram_account_id`) REFERENCES `instagram_accounts` (`id`) ON DELETE CASCADE;
ALTER TABLE `product_reviews` ADD CONSTRAINT `product_reviews_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `referral_clicks` ADD CONSTRAINT `referral_clicks_referral_id_fkey` FOREIGN KEY (`referral_id`) REFERENCES `referral_links` (`id`) ON DELETE CASCADE;
ALTER TABLE `promo_codes` ADD CONSTRAINT `promo_codes_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL;
ALTER TABLE `order_attribution_items` ADD CONSTRAINT `order_attribution_items_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE;
ALTER TABLE `order_attribution_items` ADD CONSTRAINT `order_attribution_items_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE NO ACTION;
ALTER TABLE `order_attribution_items` ADD CONSTRAINT `order_attribution_items_promo_code_id_fkey` FOREIGN KEY (`promo_code_id`) REFERENCES `promo_codes` (`id`) ON DELETE NO ACTION;
ALTER TABLE `inventory_units` ADD CONSTRAINT `inventory_units_batch_id_fkey` FOREIGN KEY (`batch_id`) REFERENCES `batches` (`id`) ON DELETE CASCADE;
ALTER TABLE `inventory_units` ADD CONSTRAINT `inventory_units_brand_id_fkey` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE SET NULL;
ALTER TABLE `inventory_units` ADD CONSTRAINT `inventory_units_demo_customer_id_fkey` FOREIGN KEY (`demo_customer_id`) REFERENCES `customers` (`id`) ON DELETE NO ACTION;
ALTER TABLE `inventory_units` ADD CONSTRAINT `inventory_units_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `inventory_units` ADD CONSTRAINT `inventory_units_sold_customer_id_fkey` FOREIGN KEY (`sold_customer_id`) REFERENCES `customers` (`id`) ON DELETE NO ACTION;
ALTER TABLE `inventory_units` ADD CONSTRAINT `inventory_units_sold_invoice_id_fkey` FOREIGN KEY (`sold_invoice_id`) REFERENCES `invoices` (`id`) ON DELETE SET NULL;
ALTER TABLE `inventory_units` ADD CONSTRAINT `inventory_units_sold_order_id_fkey` FOREIGN KEY (`sold_order_id`) REFERENCES `orders` (`id`) ON DELETE NO ACTION;
ALTER TABLE `invoice_items` ADD CONSTRAINT `invoice_items_invoice_id_fkey` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE CASCADE;
ALTER TABLE `products` ADD CONSTRAINT `products_brand_id_fkey` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE SET NULL;
ALTER TABLE `products` ADD CONSTRAINT `products_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT;
ALTER TABLE `products` ADD CONSTRAINT `products_inventory_product_id_fkey` FOREIGN KEY (`inventory_product_id`) REFERENCES `products` (`id`) ON DELETE NO ACTION;
ALTER TABLE `products` ADD CONSTRAINT `products_vendor_id_fkey` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL;
ALTER TABLE `inventory_events` ADD CONSTRAINT `inventory_events_unit_id_fkey` FOREIGN KEY (`unit_id`) REFERENCES `inventory_units` (`id`) ON DELETE CASCADE;
ALTER TABLE `dtdc_shipment_events` ADD CONSTRAINT `dtdc_shipment_events_shipment_id_fkey` FOREIGN KEY (`shipment_id`) REFERENCES `dtdc_shipments` (`id`) ON DELETE CASCADE;
ALTER TABLE `dtdc_api_logs` ADD CONSTRAINT `dtdc_api_logs_shipment_id_fkey` FOREIGN KEY (`shipment_id`) REFERENCES `dtdc_shipments` (`id`) ON DELETE SET NULL;
ALTER TABLE `invoice_batch_items` ADD CONSTRAINT `invoice_batch_items_batch_id_fkey` FOREIGN KEY (`batch_id`) REFERENCES `batches` (`id`) ON DELETE RESTRICT;
ALTER TABLE `invoice_batch_items` ADD CONSTRAINT `invoice_batch_items_invoice_id_fkey` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE CASCADE;
ALTER TABLE `invoice_batch_items` ADD CONSTRAINT `invoice_batch_items_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT;
ALTER TABLE `invoice_units` ADD CONSTRAINT `invoice_units_invoice_id_fkey` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE CASCADE;
ALTER TABLE `invoice_units` ADD CONSTRAINT `invoice_units_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT;
ALTER TABLE `invoice_units` ADD CONSTRAINT `invoice_units_unit_id_fkey` FOREIGN KEY (`unit_id`) REFERENCES `inventory_units` (`id`) ON DELETE RESTRICT;
ALTER TABLE `invoices` ADD CONSTRAINT `invoices_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `invoice_companies` (`id`) ON DELETE RESTRICT;
ALTER TABLE `product_story_blocks` ADD CONSTRAINT `product_story_blocks_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `dtdc_shipments` ADD CONSTRAINT `dtdc_shipments_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE;
ALTER TABLE `home_influencer_video_products` ADD CONSTRAINT `home_influencer_video_products_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT;
ALTER TABLE `home_influencer_video_products` ADD CONSTRAINT `home_influencer_video_products_video_id_fkey` FOREIGN KEY (`video_id`) REFERENCES `home_influencer_videos` (`id`) ON DELETE CASCADE;
ALTER TABLE `orders` ADD CONSTRAINT `orders_promo_code_id_fkey` FOREIGN KEY (`promo_code_id`) REFERENCES `promo_codes` (`id`) ON DELETE SET NULL;
ALTER TABLE `orders` ADD CONSTRAINT `orders_shipping_address_id_fkey` FOREIGN KEY (`shipping_address_id`) REFERENCES `addresses` (`id`) ON DELETE SET NULL;
ALTER TABLE `orders` ADD CONSTRAINT `orders_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `product_translations` ADD CONSTRAINT `product_translations_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `brand_translations` ADD CONSTRAINT `brand_translations_brand_id_fkey` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE CASCADE;
ALTER TABLE `category_translations` ADD CONSTRAINT `category_translations_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE;
ALTER TABLE `banner_translations` ADD CONSTRAINT `banner_translations_banner_id_fkey` FOREIGN KEY (`banner_id`) REFERENCES `home_banners` (`id`) ON DELETE CASCADE;
ALTER TABLE `product_videos` ADD CONSTRAINT `product_videos_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `order_attributions` ADD CONSTRAINT `order_attributions_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE;
ALTER TABLE `order_attributions` ADD CONSTRAINT `order_attributions_promo_code_id_fkey` FOREIGN KEY (`promo_code_id`) REFERENCES `promo_codes` (`id`) ON DELETE SET NULL;
ALTER TABLE `order_attributions` ADD CONSTRAINT `order_attributions_referral_id_fkey` FOREIGN KEY (`referral_id`) REFERENCES `referral_links` (`id`) ON DELETE SET NULL;
ALTER TABLE `product_country_prices` ADD CONSTRAINT `product_country_prices_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `carts` ADD CONSTRAINT `carts_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `cart_items` ADD CONSTRAINT `cart_items_cart_id_fkey` FOREIGN KEY (`cart_id`) REFERENCES `carts` (`id`) ON DELETE CASCADE;
ALTER TABLE `cart_items` ADD CONSTRAINT `cart_items_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `payment_orders` ADD CONSTRAINT `payment_orders_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE;
ALTER TABLE `payments` ADD CONSTRAINT `payments_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE;
ALTER TABLE `home_product_videos` ADD CONSTRAINT `home_product_videos_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL;
ALTER TABLE `wishlist_items` ADD CONSTRAINT `wishlist_items_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE;
ALTER TABLE `wishlist_items` ADD CONSTRAINT `wishlist_items_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE;
ALTER TABLE `review_votes` ADD CONSTRAINT `review_votes_review_id_fkey` FOREIGN KEY (`review_id`) REFERENCES `product_reviews` (`id`) ON DELETE CASCADE;
ALTER TABLE `instagram_messages` ADD CONSTRAINT `instagram_messages_conversation_id_fkey` FOREIGN KEY (`conversation_id`) REFERENCES `instagram_conversations` (`id`) ON DELETE CASCADE;
ALTER TABLE `facebook_ads` ADD CONSTRAINT `facebook_ads_adset_id_fkey` FOREIGN KEY (`adset_id`) REFERENCES `facebook_adsets` (`id`) ON DELETE CASCADE;
ALTER TABLE `email_campaign_category` ADD CONSTRAINT `email_campaign_category_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `email_campaign` (`id`) ON DELETE CASCADE;
ALTER TABLE `email_campaign_category` ADD CONSTRAINT `email_campaign_category_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `email_category` (`id`) ON DELETE NO ACTION;
ALTER TABLE `admin_notification_reads` ADD CONSTRAINT `admin_notification_reads_notification_id_fkey` FOREIGN KEY (`notification_id`) REFERENCES `admin_notifications` (`id`) ON DELETE CASCADE;
ALTER TABLE `email_contact_category` ADD CONSTRAINT `email_contact_category_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `email_category` (`id`) ON DELETE CASCADE;
ALTER TABLE `email_contact_category` ADD CONSTRAINT `email_contact_category_contact_id_fkey` FOREIGN KEY (`contact_id`) REFERENCES `email_contact` (`id`) ON DELETE CASCADE;
ALTER TABLE `email_unsubscribe` ADD CONSTRAINT `email_unsubscribe_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `email_campaign` (`id`) ON DELETE NO ACTION;
ALTER TABLE `facebook_adsets` ADD CONSTRAINT `facebook_adsets_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `facebook_campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `email_campaign_recipient` ADD CONSTRAINT `email_campaign_recipient_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `email_campaign` (`id`) ON DELETE CASCADE;
ALTER TABLE `email_campaign_recipient` ADD CONSTRAINT `email_campaign_recipient_contact_id_fkey` FOREIGN KEY (`contact_id`) REFERENCES `email_contact` (`id`) ON DELETE NO ACTION;
ALTER TABLE `customers` ADD CONSTRAINT `customers_vendor_id_fkey` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE CASCADE;
ALTER TABLE `whatsapp_campaign_messages` ADD CONSTRAINT `whatsapp_campaign_messages_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `whatsapp_campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `whatsapp_campaign_messages` ADD CONSTRAINT `whatsapp_campaign_messages_contact_id_fkey` FOREIGN KEY (`contact_id`) REFERENCES `whatsapp_contacts` (`id`) ON DELETE CASCADE;
ALTER TABLE `whatsapp_campaigns` ADD CONSTRAINT `whatsapp_campaigns_template_id_fkey` FOREIGN KEY (`template_id`) REFERENCES `whatsapp_templates` (`id`) ON DELETE RESTRICT;
ALTER TABLE `pincodes` ADD CONSTRAINT `pincodes_zone_fkey` FOREIGN KEY (`zone`) REFERENCES `shipping_zones` (`zone`) ON DELETE NO ACTION;
ALTER TABLE `home_product_video_products` ADD CONSTRAINT `home_product_video_products_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT;
ALTER TABLE `home_product_video_products` ADD CONSTRAINT `home_product_video_products_video_id_fkey` FOREIGN KEY (`video_id`) REFERENCES `home_product_videos` (`id`) ON DELETE CASCADE;
ALTER TABLE `invoice_payments` ADD CONSTRAINT `invoice_payments_invoice_id_fkey` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;
